### ISSUE TITLE
then-redis yarn warning

### ISSUE THREAD

**Issue by maprules1000** [ember-cli-deploy/ember-cli-deploy-redis#74]
When using yarn to manage packages it throws the following warning:
`warning "then-redis@2.0.1" has unmet peer dependency "redis-commands@*".`

and the `then-redis` maintainer has [announced](https://github.com/mjackson/then-redis) he is no longer maintaining `then-redis` and that users should switch to [`node_redis`](https://github.com/NodeRedis/node_redis) which now contains promise goodness.

So, is it possible to drop `then-redis` and replace it with `node_redis`?

**Comment by ghedamat** [comment]
@maprules1000 it should definitely be possible but might be a bit of work.

would you be interested trying to submit a PR? I'm sure the ECD team is willing to help you out if you decide to do so. You can find us in the `ec-deploy` channel of the ember-community slack.

if you're busy no worries! We'll try to get to it soon anyway, it's been on the list for a long time..

**Comment by maprules1000** [comment]
Yup, I will find some time for it @ghedamat!

**Comment by lukemelia** [comment]
Unfortunately, I had to revert #74. While the tests passed (because the redis library is mocked in the tests), the plugin doesn't actually work. The methods in the `redis` package's client implementation do not return promises, as they do in then-redis. Our code expects the return values to be promises. @maprules1000 or someone else will need to take another attempt at this.

**Comment by blimmer** [comment]
See #86
